### ISSUE TITLE
Images missing for default achievments

### ISSUE THREAD

**Issue by mnoreke** [Handyfon/Farchievements#47]
Foundry Virtual Tabletop: Version 10, 10.291
Game System: dnd5e, 2.0.3

![image](https://user-images.githubusercontent.com/5225366/205970616-3ef140d7-23fb-4a01-b17e-e84f0838e954.png)

**Comment by Handyfon** [comment]
Fixed in 10.2?
You may have to reset the settings

**Comment by mnoreke** [comment]
Still not resolved. I removed and readded the module, no changes.

It appears that the missing icons are pointing towards "user content" instead of "core content" as foundry only expects "icons/skills/wounds/injury-eyes-blood-red-pink.webp" (hardmode icon) as a path for core items. The missing ones have "system/dnd5e/" in front of that (warning that pops up).

Side note: If you are pulling icons from dnd5e and not your own module, then that should be listed a dependency in the module.json file with a version number to ensure icons are there.

**Comment by Handyfon** [comment]
I thinks it's because it already generated the new data structure for you. I changed the standard Icons in the last update.

**Comment by mnoreke** [comment]
That did resolve it. To note, I have never used Foundry V9, so initial data creation appears to still have used V9 data for V10.

**Comment by JTThurn** [comment]
Hi there!

Just wanted to note that in my case the issue was the filename extension. The settings had it listed as modules/farchievements/mystery.**JPG**, but the actual file is modules/farchievements/mystery.**jpg**.

**Comment by krobibero** [comment]
I just installed Farchievements on my v10, build 291 and immediately encountered this bug.  My Foundry is running on a Linux server, so file name capitalization matters.  The Mystery Icon configuration has JPG however the file name is jpg.  Changing the config from JPG to jpg fixed the problem for me.

**Comment by Handyfon** [comment]
will be fixed in 14.4
